name: Salesforce Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias target-org

      - name: Download Job ID
        uses: actions/download-artifact@v3
        with:
          name: deploy-job-id

      - name: Quick Deploy
        run: |
          JOB_ID=$(cat job_id.txt)
          echo "Using JOB_ID=$JOB_ID"
          sf project deploy quick --job-id $JOB_ID