name: Deploy Salesforce

on:
    push:
        branches:
            - develop
            - release/*

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Install Salesforce CLI
              run: npm install -g @salesforce/cli

            - name: Authenticate org
              run: |
                echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
                sf org login sfdx-url --sfdx-url-file auth.txt --alias target-org

            - name: Deploy org DEV
              run: | 
                sf project deploy start /
                 --source-dir force/app /
                 --target-org target-org /
                 --test-level RunLocalTests

            