# Nome unico per questo workflow
name: Validate Salesorce

# Definizione di quando il workflow viene lanciato
on:
    # the workflow will run whenever an event happens on a pull request 
    pull_request: 
        # the events are that a PR is opened, or when a commit is pushed 
        # to a branch tha has an existing pull request
        types: [opened, synchronize ]
        # the branches filter alloes to specify tha this workflow should only 
        #run if the branch name is "staging".this way we prevent this workflow 
        # from running when Prs are opened on other branches
        branches: [ staging ]
        # we only care about changes to the force-app directory, wich is the 
        # root directory of the sfdx project. thi prevents the job from running 
        # when changing non-salesforce files (like this yml file).
        paths:
            - 'force-app/**'

jobs: 
    validate: 
        runs-on: ubuntu-latest
        steps: 
